version: "3.8"
services:
  boom:
    depends_on:
      - storage
      - kvstorage
    build: ./boom
    restart: on-failure
    entrypoint: ["/app/start.sh"]
    ports:
      - "3001:3001"
    environment:
      - "REDIS_URL=redis://kvstorage:6379/15"
      - "REDIS_PROVIDER=REDIS_URL"
      - "DATABASE_URL=postgres://postgres:whatever@storage:5432/boom_development"
      - "BOOM_TEST_DATABASE_HOST=storage"
      - "BOOM_TEST_DATABASE_PORT=5432"
      - "BOOM_TEST_DATABASE_USERNAME=postgres"
      - "BOOM_TEST_DATABASE_PASSWORD=whatever"
      - "BOOM_CORS_DOMAIN=localhost:3002"
  poke:
    depends_on:
      - boom
    build:
      context: ./poke
      args:
        - "boom_url=http://localhost:3001/v1"
    restart: always
    entrypoint: ["/app/start.sh"]
    ports:
      - "3002:3002"
    environment:
      - "PORT=3002"
      - "REACT_APP_BOOM_URL=http://localhost:3001/v1"
  kvstorage:
    image: redis:6.0.3-alpine3.11
    restart: always
    ports:
      - "6400:6379"
  storage:
    build: ./storage
    restart: always
    shm_size: 256M
    ports:
      - "5400:5432"
    environment:
      - "POSTGRES_PASSWORD=whatever"
