# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'bcrypt', '~> 3.1'
gem 'devise', '~> 4.7'
gem 'devise-jwt', '~> 0.6'
gem 'jsonapi-rails', '~> 0.4'
gem 'pg', '~> 1.2'
gem 'puma', '~> 4.1'
gem 'rack-cors', '~> 1.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.1'
gem 'redis', '~> 4.1'
gem 'redis-namespace', '~> 1.7'

group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'rubocop', '~> 0.84.0', require: false
  gem 'rubocop-rails', '~> 2.5.2', require: false
end
